# shibcert.yml: shibcert application user-specific configuration


caption_j:
  site_title: "京都大学 個人証明書発行申請システム"
  purpose_type:
    # 4: Client Certification SHA1, 5: Client Certification SHA1
    # 6: S/MIME Certificatino SHA2, 7: S/MIME Certification SHA2
    5: "学内ネットワーク(KUINS)認証用 クライアント証明書"  
    7: "全学メール(KUMAIL,KUMOI)用 S/MIME証明書"
  purpose_type_short:
    5: "KUINS用 クライアント証明書"  
    7: "全学メール用 S/MIME証明書"
caption_e:
  site_title: "Kyoto University Personal Certification Application System"  
  purpose_type:
    # 4: Client Certification SHA1, 5: Client Certification SHA2 
    # 6: S/MIME Certificatino SHA2, 7: S/MIME Certification SHA2
    5: "Client Certification for Campus Netork(KUINS) Authentication"  
    7: "S/MIME Certification for Campus Mail(KUMAIL, KUMOI)"
  purpose_type_short:
    5: "Client Cert for KUINS"  
    7: "S/MIME Cert for Campus Mail"


development:
  certificate_file: "config/certificates/client.cer"
  certificate_key_file:  "config/certificates/client.key"

  cert_download_type: '1'
  admin_name: 'shibcert.iimc.kyoto-u.ac.jp'
  admin_ou: 'Institute for Information Management and Communication'
  admin_mail: 'shibcert@iimc.kyoto-u.ac.jp'
  user_ou: 'Institute for Information Management and Communication'

